[_]
schema-version = "0.2"

[project]
id = "keda-external-pubsub"
name = "KEDA External Pub/Sub Scaler"
version = "0.1.0"

[io.buildpacks]
builder = "paketobuildpacks/builder-jammy-buildpackless-static"

[[io.buildpacks.build.env]]
name = "CGO_ENABLED"
value = "0"

[[io.buildpacks.build.env]]
name = "BP_GO_BUILD_FLAGS"
value = "-buildmode=default"

[[io.buildpacks.build.env]]
name = "BP_GO_TARGETS"
value = "."

[[io.buildpacks.group]]
id = "paketo-buildpacks/go"
